### PR TITLE
A spectral method for nonlocal diffusion operators on the sphere

### PR DESCRIPTION
**Pull request by MikaelSlevinsky**
This adds almost all of the code required to generate the figures and
data of the so-titled preprint with @Hadrien-Montanelli and Qiang Du:

https://arxiv.org/abs/1801.04902

As this repository grows, it’s anticipated that the code will take on
more of an OOP-style consistent with the rest of JuliaApproximation. So
for now (and with highly optimized fixed temporal and spatial
discretizations), this code could be considered for benchmarking
purposes.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Cool to see. We're building exponential integrators in DiffEq and found some interesting things about computing the coefficients:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/242

The Taylor expansion there, that would work for general (non-diagonal) linear operators as well? If so I'm gonna start benchmarking it.

**Comment by MikaelSlevinsky** [comment]
In principle, yes, so long as the argument to the Taylor series is a matrix. But the Taylor series works best for diagonal problems. For non diagonal problems, there are a couple options; see, for example, https://ora.ox.ac.uk/objects/uuid:cc001282-4285-4ca2-ad06-31787b540c61. For problems with aperiodic boundary conditions, there is still room to explore.

**Comment by ChrisRackauckas** [comment]
Huh, interesting paper. Thanks!

**Comment by dlfivefifty** [comment]
Looks cool Mikael! We should probably decide what the point of this repository is.

PS I have a student looking at adding spherical harmonics to ApproxFun at the moment.

**Pull request merged**
